### ISSUE TITLE
(hash) works in a file, but not by itself in the REPL

### ISSUE THREAD

**Issue by SanAngeloMike** [jbr/sibilant#89]
sibilant> (hash)
TypeError: sibilant.macros.scoped is not a function
    at /Users/jbr/code/sibilant/src/repl.sibilant:40:50
    at /Users/jbr/code/sibilant/src/repl.sibilant:40:21
    at Interface.handleLine$ (/Users/jbr/code/sibilant/src/repl.sibilant:35:6)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface._line (readline.js:549:8)
    at Interface._ttyWrite (readline.js:826:14)
    at ReadStream.onkeypress (readline.js:105:10)
    at emitTwo (events.js:87:13)
sibilant> (var g (hash))
var g = {  };

(hash) works fine in a file.

**Comment by jbr** [comment]
Thanks for reporting, I'll get a fix out asap.  My hypothesis is that node is interpreting `{}` as a block for some reason.
