### ISSUE TITLE
`(include "module")` doesn't seem to work as described.

### ISSUE THREAD

**Issue by riatzukiza** [jbr/sibilant#96]
I attempted the example in the documentation for "sibilant-react", and on macro libs I'd written my self, and it does not seem to resolve.

**Comment by riatzukiza** [comment]
I think this may have to do with:
```lisp
(def create-context ()
     (var context (vm.create-context))
     (set module 'filename (pipe (process.cwd) (concat "/exec")))
     (set context
          '*sibilant sibilant
          'module  module
          'require require)
     (each-key key global (set context key (get global key)))
     context)
```

this is from the repl file, but it causes a similar kind of issue as what I see with inclusion for the require statement, in that it cannot find modules. It is looking from them from the directory that sibilant is installed, not from where it is run.

I have fixed problems like this before in custom module systems I've build for http servers, I'll be seeing what I can do with this.

**Comment by riatzukiza** [comment]
```clojure
(def create-context ()
  (var context (vm.create-context)
       cwd (process.cwd))

  (set module 'filename (pipe cwd (concat "/exec")))

  (var p "/")
  (assign module.paths [
          ...module.paths
          ...(.map (.split cwd path.sep)
                   (lambda (el)
                     (var r (path.join p "node_modules"))
                     (assign p (path.join p el)) r))
          cwd
          (path.join cwd "node_modules")
          ])
  (set context
       '*sibilant sibilant
       'module  module
       'require (modded-require (process.cwd)))
  (each-key key global (set context key (get global key)))
  context)
```
I have made the following modifications to the create context function, it can find the modules properly inside of a repl context. Much better! now the repls actually useful.

**Comment by riatzukiza** [comment]
The above example is not what was used in the fork to fix this, I'd originally thought I could fix it like I had fixed another similar problem with requiring in dynamic contexts, and temporarily borrowed it.
```cljs
(macro add-to-module-lookup (path)
       `(scoped (require! 'path)
                (var p "/"
                     inc @(or path (process.cwd)))
                (assign module.paths [
                        ...module.paths
                        ...(.map (.split inc path.sep)
                                 (lambda (el)
                                   (var r (path.join p "node_modules"))
                                   (assign p (path.join p el)) r))
                        (path.join inc "node_modules")
                        ])))
```
there is now a macro that can be used any where to add a new path to the require look up.

**Comment by riatzukiza** [comment]
I thought this would have fixed the inclusion issue as well, but its a no go.
```
sibilant> (include "sibilant-react")
(include "sibilant-react")

/home/aaron/devel/by-lang/js/sibilant/maps/src/repl.sibilant:96
(readline.on 'line handle-line)
                   ^
TypeError: Cannot read property 'match' of undefined
    at Interface.<anonymous> (/home/aaron/devel/by-lang/js/sibilant/maps/src/repl.sibilant:96:20)
    at Interface.<anonymous> (/home/aaron/devel/by-lang/js/sibilant/lib/repl.js:128:10)
    at Interface.handleLine$ (/home/aaron/devel/by-lang/js/sibilant/lib/repl.js:130:6)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:239:10)
    at Interface._line (readline.js:585:8)
    at Interface._ttyWrite (readline.js:869:16)
    at ReadStream.onkeypress (readline.js:126:10)
    at emitTwo (events.js:106:13)
```

**Comment by riatzukiza** [comment]
Not sure why the above was happening... maybe I've now changed somthing else that magically fixed it, not sure.
